name: Update Radio Metadata

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch HTML
        run: |
          curl -s http://uk15freenew.listen2myradio.com:4243/ > raw.html
          head -n 20 raw.html

      - name: Run parser
        run: python3 parse.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add metadata.json
          git commit -m "update metadata" || echo "Sin cambios"
          git push
